### ISSUE TITLE
Error: Cannot find module 'error-tojson'

### ISSUE THREAD

**Issue by abdulmyanov** [meefik/ITMOproctor#38]
Добрый день!
Вот вывод терминала после запуска. Однако по адресу localhost:3000 ничего не появляется. Как понять, работает сервер или нет? В чем проблема?

```
admin1@proctor:~/ITMOproctor$ npm start

> proctor-server@0.7.0 start /home/admin1/ITMOproctor
> node ./bin/www

`open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
2017-08-11T12:14:16.307Z - error: uncaughtException: Cannot find module 'error-tojson' date=Fri Aug 11 2017 16:14:16 GMT+0400 (SAMT), pid=1803, uid=1000, gid=1000, cwd=/home/admin1/ITMOproctor, execPath=/usr/bin/nodejs, version=v0.12.18, argv=[node, /home/admin1/ITMOproctor/bin/www], rss=179945472, heapTotal=72151552, heapUsed=46921488, loadavg=[0.08642578125, 0.056640625, 0.05078125], uptime=921
# Error: Cannot find module 'error-tojson'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/admin1/ITMOproctor/node_modules/kurento-client/lib/index.js:27:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/home/admin1/ITMOproctor/webrtc/webcall.js:3:15)
    at module.exports (/home/admin1/ITMOproctor/webrtc/index.js:3:5)
    at Object.<anonymous> (/home/admin1/ITMOproctor/server.js:105:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
2017-08-11T12:14:16.323Z - info: MongoDb is connected
```

**Comment by meefik** [comment]
Обновите node до версии 4.x

**Comment by abdulmyanov** [comment]
Ситуация не изменилась((

```
admin1@proctor:~$ node -v
v4.0.0
admin1@proctor:~$ cd ./ITMOproctor
admin1@proctor:~/ITMOproctor$ npm start

> proctor-server@0.7.0 start /home/admin1/ITMOproctor
> node ./bin/www

`open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
2017-08-11T12:38:39.058Z - error: uncaughtException: Cannot find module 'error-tojson' date=Fri Aug 11 2017 16:38:39 GMT+0400 (SAMT), pid=1270, uid=1000, gid=1000, cwd=/home/admin1/ITMOproctor, execPath=/home/admin1/.nvm/versions/node/v4.0.0/bin/node, version=v4.0.0, argv=[/home/admin1/.nvm/versions/node/v4.0.0/bin/node, /home/admin1/ITMOproctor/bin/www], rss=169320448, heapTotal=69211136, heapUsed=44308936, loadavg=[0.1865234375, 0.05859375, 0.021484375], uptime=68
Error: Cannot find module 'error-tojson'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/admin1/ITMOproctor/node_modules/kurento-client/lib/index.js:27:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/home/admin1/ITMOproctor/webrtc/webcall.js:3:15)
    at module.exports (/home/admin1/ITMOproctor/webrtc/index.js:3:5)
    at Object.<anonymous> (/home/admin1/ITMOproctor/server.js:105:20)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
2017-08-11T12:38:39.075Z - info: MongoDb is connected

```

**Comment by meefik** [comment]
Попробуйте установить недостающий модуль:
```
npm install error-tojson
```

**Comment by abdulmyanov** [comment]
Установил, после чего при запуске он выводит ту же ошибку об отсутствии модулей async, потом, extend, es6-promise,  promisecallback и т.д.......

**Comment by meefik** [comment]
Перед запуском нужно выполнить установку всех зависимостей:
```
npm install
```

**Comment by abdulmyanov** [comment]
После установки зависимостей та же ошибка... Только с другим модулем.

```
admin1@proctor:~/ITMOproctor/db$ npm install error-tojson
error-tojson@0.0.1 ../node_modules/error-tojson
admin1@proctor:~/ITMOproctor/db$ npm install

> proctor-server@0.7.0 postinstall /home/admin1/ITMOproctor
> cd ./public && bower install

admin1@proctor:~/ITMOproctor/db$ npm start

> proctor-server@0.7.0 start /home/admin1/ITMOproctor
> node ./bin/www

`open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
2017-08-11T13:05:39.287Z - error: uncaughtException: Cannot find module 'async' date=Fri Aug 11 2017 17:05:39 GMT+0400 (SAMT), pid=13435, uid=1000, gid=1000, cwd=/home/admin1/ITMOproctor, execPath=/usr/bin/nodejs, version=v4.8.4, argv=[/usr/bin/nodejs, /home/admin1/ITMOproctor/bin/www], rss=174444544, heapTotal=70243072, heapUsed=40976944, external=117343329, loadavg=[0.26416015625, 0.3173828125, 0.16650390625], uptime=527
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/admin1/ITMOproctor/node_modules/kurento-client/lib/MediaObjectCreator.js:17:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/admin1/ITMOproctor/node_modules/kurento-client/lib/index.js:32:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
2017-08-11T13:05:39.304Z - info: MongoDb is connected
```

**Comment by meefik** [comment]
Установку модулей нужно производить из корневой директории проекта.

**Comment by abdulmyanov** [comment]
И из корневой директории та же ситуация((( 

```
admin1@proctor:~/ITMOproctor$ npm install error-tojson
error-tojson@0.0.1 node_modules/error-tojson
admin1@proctor:~/ITMOproctor$ npm install

> proctor-server@0.7.0 postinstall /home/admin1/ITMOproctor
> cd ./public && bower install

admin1@proctor:~/ITMOproctor$ npm start

> proctor-server@0.7.0 start /home/admin1/ITMOproctor
> node ./bin/www

`open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
2017-08-11T13:10:28.297Z - error: uncaughtException: Cannot find module 'async' date=Fri Aug 11 2017 17:10:28 GMT+0400 (SAMT), pid=13532, uid=1000, gid=1000, cwd=/home/admin1/ITMOproctor, execPath=/usr/bin/nodejs, version=v4.8.4, argv=[/usr/bin/nodejs, /home/admin1/ITMOproctor/bin/www], rss=173101056, heapTotal=70243072, heapUsed=40973864, external=117343329, loadavg=[0.09814453125, 0.158203125, 0.1337890625], uptime=816
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/admin1/ITMOproctor/node_modules/kurento-client/lib/MediaObjectCreator.js:17:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/admin1/ITMOproctor/node_modules/kurento-client/lib/index.js:32:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
2017-08-11T13:10:28.314Z - info: MongoDb is connected
```

**Comment by meefik** [comment]
Попробуйте удалить все модули и установить заново:
```
rm -rf ./node_modules
npm install
```

**Comment by abdulmyanov** [comment]
```
admin1@proctor:~/ITMOproctor$ rm -rf ./node_modules
admin1@proctor:~/ITMOproctor$ npm install
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN engine geoip-lite@1.2.1: wanted: {"node":">=5.10.0"} (current: {"node":"4.8.4","npm":"2.15.11"})
npm WARN deprecated mongodb@2.0.55: Please upgrade to 2.2.19 or higher
npm WARN peerDependencies The peer dependency kerberos@~0.0 included from mongodb-core will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> kerberos@0.0.23 install /home/admin1/ITMOproctor/node_modules/connect-mongo/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Вход в каталог `/home/admin1/ITMOproctor/node_modules/connect-mongo/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: Нет такого файла или каталога
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Ошибка 1
make: Выход из каталога `/home/admin1/ITMOproctor/node_modules/connect-mongo/node_modules/mongodb/node_modules/kerberos/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.2.0-27-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/admin1/ITMOproctor/node_modules/connect-mongo/node_modules/mongodb/node_modules/kerberos
gyp ERR! node -v v4.8.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

**Comment by abdulmyanov** [comment]
Ура, работает! Спасибо за помощь! =)
