### ISSUE TITLE
Аутентификация через edx

### ISSUE THREAD

**Issue by eazaika** [meefik/ITMOproctor#40]
Пытаемся припилить oauth2-аутентификацию от open.etu.ru (edx ginkgo.1) по примеру openedu. 
```
InternalOAuthError: failed to fetch user profile
    at /home/eazaika/ITMOproctor/routes/profile.js:94:25
    at ClientRequest.<anonymous> (/path-to/ITMOproctor/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:162:5)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at connectErrorNT (net.js:1016:8)
    at nextTickCallbackWith2Args (node.js:511:9)
    at process._tickDomainCallback (node.js:466:17)
```
Заметили такое отличие: openedu в куках для proctor.ifmo.ru отправляет два поля (athenticated=1 и authenticated_user=username). Наш же open.etu.ru отдает поля edxloggedin=true и edx-user-info="вот тут большущий json с username и прочим".

Соответственно вопрос: где в коде проктора мы должны внести изменения в названии отслеживаемых полей и как же вытянуть пресловутый username из ответа? (grep по 'authenticated' находит просто уйму вхождений, а по 'authenticated_user' - ни одного)

**Comment by meefik** [comment]
Получение профиля через OAuth происходит в строчке https://github.com/meefik/ITMOproctor/blob/master/routes/profile.js#L90

Проверьте настройки авторизации в конфигурационном файле https://github.com/meefik/ITMOproctor/blob/master/config-example.json#L33

Возможно, поменялся формат JSON возвращаемого профиля, тогда это нужно править тут https://github.com/meefik/ITMOproctor/blob/master/db/index.js#L47

**Comment by eazaika** [comment]
cookie
```
_ym_uid=***; 
_ga=***; 
openedx-language-preference=ru;
 _ym_d=***; 
_gid=***;
 _ym_isad=2; 
edxloggedin=true; 
_ym_visorc_47949185=w; 
authenticated=true; 
_gat_gtag_UA_114846701_1=1; 
csrftoken=***; 
edx-user-info="{\"username\": \"testuser\"}"; 
sessionid="***"
```
routes/profile.js
```
// OAuth2 strategy (LETIteach)
passport.use('LETIteach', new OAuth2Strategy({
    authorizationURL: config.get('auth:LETIteach:authorizationURL'),
    tokenURL: config.get('auth:LETIteach:tokenURL'),
    clientID: config.get('auth:LETIteach:clientID'),
    clientSecret: config.get('auth:LETIteach:clientSecret'),
    callbackURL: config.get('auth:LETIteach:callbackURL'),
    scope: config.get('auth:LETIteach:scope')
}, function(accessToken, refreshToken, prof, done) {
    var userProfileURL = config.get('auth:LETIteach:userProfileURL');
    this._oauth2._useAuthorizationHeaderForGET = true;
    this._oauth2.get(userProfileURL, accessToken, function(err, body, res) {
        if (err) {
            var InternalOAuthError = require('passport-oauth').InternalOAuthError;
            return done(new InternalOAuthError('failed to fetch user profile', err));
        }
        try {
            db.profile.auth.LETIteach(JSON.parse(body), done);
        }
        catch (e) {
            done(e);
        }
    });
}));
router.get('/LETIteach', passport.authenticate('LETIteach'));
router.get('/LETIteach/callback', passport.authenticate('LETIteach', {
    failureRedirect: '/#login'
}), router.logUserIP, function(req, res, next) {
    res.redirect('/');
});
```
config.js
```
"auth": {
        "LETIteach": {
            "authorizationURL": "https://open.etu.ru/oauth2/auth",
            "tokenURL": "https://open.etu.ru/oauth2/token",
            "userProfileURL": "https://open.edu.ru/oauth2/user_info",
            "clientID": "test",
            "clientSecret": "test",
            "callbackURL": "https://proctor.etu.ru/profile/LETIteach/callback",
            "scope": "openid profile email"
        },
```
db/index.js
```
LETIteach: function(prof, done) {
                var userData = {
                    username: prof.username,
                    provider: config.get('auth:LETIteach:provider') || 'LETIteach'
                };
                var User = require('./models/user');
                User.findOne({
                    username: userData.username,
                    provider: userData.provider
                }).exec(function(err, data) {
                    if (err) {
                        return done(err);
                    }
                    if (!data) {
                        var user = new User(userData);
                        user.save(function(err, data) {
                            return done(err, data);
                        });
                    }
                    else {
                        if (!data.isActive()) {
                            return done(null, false, {
                                message: 'User is inactive.'
                            });
                        }
                        return done(null, data);
                    }
                });
            },
```
Ситуация на данный момент. Ошибка прежняя

**Comment by meefik** [comment]
Попробуйте связаться с разработчиками из ИТМО, они поддерживают форк https://github.com/openeduITMO/ITMOproctor
Я больше не занимаюсь поддержкой этого проекта.
