### ISSUE TITLE
Failed to query stereo recording.

### ISSUE THREAD

**Issue by alexaasha** [meefik/ITMOproctor#45]
**Не включается веб-камера при проверке. Ubuntu 20 LTS.
Полный текст:**

[320106:320106:1019/180031.133462:ERROR:sandbox_linux.cc(348)] InitializeSandbox() called with multiple threads in process gpu-process.
https://itmoproctor.openedu.ru/bower_components/jeasyui/jquery.easyui.min.js:3128
var opts=_240.options;
              ^

TypeError: Cannot read property 'options' of undefined
    at _23d (https://itmoproctor.openedu.ru/bower_components/jeasyui/jquery.easyui.min.js:3128:15)
    at HTMLDivElement.<anonymous> (https://itmoproctor.openedu.ru/bower_components/jeasyui/jquery.easyui.min.js:3309:1)
    at Function.each (https://itmoproctor.openedu.ru/bower_components/jquery/dist/jquery.min.js:2:2975)
    at m.fn.init.each (https://itmoproctor.openedu.ru/bower_components/jquery/dist/jquery.min.js:2:835)
    at Object.destroy (https://itmoproctor.openedu.ru/bower_components/jeasyui/jquery.easyui.min.js:3308:11)
    at m.fn.init.$.fn.panel (https://itmoproctor.openedu.ru/bower_components/jeasyui/jquery.easyui.min.js:3259:32)
    at m.fn.init.$.fn.window (https://itmoproctor.openedu.ru/bower_components/jeasyui/jquery.easyui.min.js:3614:13)
    at m.fn.init.$.fn.dialog (https://itmoproctor.openedu.ru/bower_components/jeasyui/jquery.easyui.min.js:3765:13)
    at https://itmoproctor.openedu.ru/bower_components/jeasyui/jquery.easyui.min.js:3870:5
[320121:320219:1019/180056.595706:ERROR:adm_helpers.cc(62)] Failed to query stereo recording.
ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_usb_stream.c:508:(_snd_pcm_usb_stream_open) Unknown field hint

**Comment by meefik** [comment]
Вероятно, проблема исправлена в EasyUI 1.9.15
