### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by meefik** [meefik/ITMOproctor#5]
На сервере появляется предупреждение:
```
(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at MongoStore.addListener (events.js:239:17)
    at MongoStore.once (events.js:265:8)
    at MongoStore.getCollection (/home/ubuntu/workspace/node_modules/connect-mongo/lib/connect-mongo.js:219:16)
    at MongoStore.get (/home/ubuntu/workspace/node_modules/connect-mongo/lib/connect-mongo.js:285:10)
    at Array.<anonymous> (/home/ubuntu/workspace/node_modules/passport.socketio/lib/index.js:69:16)
    at run (/home/ubuntu/workspace/node_modules/socket.io/lib/namespace.js:114:11)
    at Namespace.run (/home/ubuntu/workspace/node_modules/socket.io/lib/namespace.js:126:3)
    at Namespace.add (/home/ubuntu/workspace/node_modules/socket.io/lib/namespace.js:155:8)
    at Client.connect (/home/ubuntu/workspace/node_modules/socket.io/lib/client.js:74:20)
    at Server.onconnection (/home/ubuntu/workspace/node_modules/socket.io/lib/index.js:315:10)
    at emitOne (events.js:77:13)
    at Server.emit (events.js:169:7)
    at Server.handshake (/home/ubuntu/workspace/node_modules/socket.io/node_modules/engine.io/lib/server.js:262:8)
    at /home/ubuntu/workspace/node_modules/socket.io/node_modules/engine.io/lib/server.js:184:12
    at Server.checkRequest (/home/ubuntu/workspace/node_modules/socket.io/lib/index.js:68:51)
    at Server.verify (/home/ubuntu/workspace/node_modules/socket.io/node_modules/engine.io/lib/server.js:127:17)
```

**Comment by meefik** [comment]
Это нормальное поведение сервера. Сообщение обычно появлявляется после перезагрузки сервера, если есть активные клиенты. Сокеты клиентов начинают одновремменно подключаться к серверу, а если есть активные экзамены, то обновляются данные в members, что приводит к множественным запросам в mongodb.
